# Copyright Notice:
# Copyright 2016-2024 DMTF. All rights reserved.
# License: BSD 3-Clause License. For full text see link: https://github.com/DMTF/python-redfish-library/blob/main/LICENSE.md

---
version: "3.7"

services:

  bmc:
    image: docker.io/dmtf/redfish-mockup-server:latest
    networks:
      - dmtf

  test:
    image: docker.io/curlimages/curl:8.5.0
    depends_on:
      bmc:
        condition: service_healthy
    networks:
      - dmtf
    command: ["--fail", "-i", "-H", "Accept:application/yang-data+json", "http://bmc:8000/redfish/v1/Managers"]

  bmc-ssl:
    image: docker.io/dmtf/redfish-mockup-server:latest
    networks:
      - dmtf
    entrypoint: ["/bin/bash"]
    command: |
      -x -c '
      openssl req -x509 -nodes -newkey rsa:2048 -keyout key.pem -out cert.pem -sha256 -days 365 -subj "/C=GB/ST=London/L=London/O=Alros/OU=IT Department/CN=localhost" && \
      python /usr/src/app/redfishMockupServer.py -H 0.0.0.0 --ssl --key ./key.pem --cert ./cert.pem --port 9000'
    healthcheck:
      test: curl --insecure --fail https://localhost:9000/redfish/

  test-ssl:
    image: docker.io/curlimages/curl:8.5.0
    depends_on:
      bmc-ssl:
        condition: service_healthy
    networks:
      - dmtf
    command: ["--fail", "--insecure", "-i", "-H", "Accept:application/yang-data+json", "https://bmc-ssl:9000/redfish/v1/Managers"]


networks:
  dmtf:
